name: Github Actions Demo

on:
  push:
    branches: 
      - main
    paths-ignore: 
      - .github/**
  pull_request:
    branches: 
      - main
  schedule:
    - cron: 15 6 * * 0
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "Workflow triggered by this type of event: ${{ github.event_name }}"
          echo "The triggered branch is: ${{ github.event.ref }}"
      
      - uses: actions/checkout@v3
      
      - name: List all files in the directory
        run: |
          echo "# List of files in the directory" >> $GITHUB_STEP_SUMMARY
          tree
    
